# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda013869907d0db96191d5f1b59bdc84d36d1785c6eb914dc7961cdbf394638f70f164b92b1d88f89f41de9db370863f655daad2c4b90405df2b66af86d16d8

test:
  secret_key_base: 065e6585c7a7ebcd0ef852255de248674ec57ea12ed4d1fae4545e59ca4ae787819a07dccde4e6ca738a57c7dd88de21e5540304335a9a992b51c57f30de89ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
